//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class abc
    {
        public int id { get; set; }
        public int a { get; set; }
        public Nullable<double> b { get; set; }
        public string c { get; set; }
        public Nullable<System.DateTime> d { get; set; }
        public string e { get; set; }
    }
}
