//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemoDocTable
    {
        public int Id { get; set; }
        public string DocOwner { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public Nullable<int> Importance { get; set; }
        public string DocPath { get; set; }
    }
}
