//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingCampaignEffectiveness
    {
        public int McEffId { get; set; }
        public string ProfileID { get; set; }
        public string SessionStart { get; set; }
        public string Duration { get; set; }
        public string State { get; set; }
        public string SrcIPAddress { get; set; }
        public string GameType { get; set; }
        public string Multiplayer { get; set; }
        public string EndRank { get; set; }
        public string WeaponsUsed { get; set; }
        public string UsersInteractedWith { get; set; }
        public int Impressions { get; set; }
    }
}
