//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class patient
    {
        public int patientId { get; set; }
        public string name { get; set; }
        public Nullable<int> room { get; set; }
        public Nullable<int> wing { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
    }
}
