//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class sample_table
    {
        public int c1 { get; set; }
        public string c2 { get; set; }
        public Nullable<System.DateTime> c3 { get; set; }
    }
}
