//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class t1
    {
        public int col1 { get; set; }
        public Nullable<int> col2 { get; set; }
        public byte[] col3 { get; set; }
    }
}
