//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSample
    {
        public int Id { get; set; }
        public string DeviceID { get; set; }
        public Nullable<System.DateTime> Dt { get; set; }
        public Nullable<long> Tick { get; set; }
        public string SampleType { get; set; }
        public string SampleValue { get; set; }
    }
}
