//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkLog
    {
        public int Id { get; set; }
        public System.DateTime DtAdd { get; set; }
        public byte[] Ts { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public string Notes { get; set; }
        public decimal TelemetryMs { get; set; }
    }
}
