//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkOrderToArticle
    {
        public int Id { get; set; }
        public int IdArticle { get; set; }
        public int IdOrder { get; set; }
        public System.DateTime DtAdd { get; set; }
        public byte[] Ts { get; set; }
        public decimal Count { get; set; }
        public decimal TotalPrice { get; set; }
        public double Width { get; set; }
        public double Height { get; set; }
        public string Notes { get; set; }
    
        public virtual tkArticle tkArticle { get; set; }
        public virtual tkOrder tkOrder { get; set; }
    }
}
