//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2016SQLDayDemoEF6.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tkViewAll
    {
        public int Id { get; set; }
        public int IdArticle { get; set; }
        public int IdOrder { get; set; }
        public decimal Count { get; set; }
        public System.DateTime tkOrderToArticle_DtAdd { get; set; }
        public double Height { get; set; }
        public string Notes { get; set; }
        public decimal TotalPrice { get; set; }
        public string BlobImageUrl { get; set; }
        public System.DateTime tkArticles_DtAdd { get; set; }
        public string LongDescription { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public System.DateTime tkOrders_DtAdd { get; set; }
        public string OrderNo { get; set; }
    }
}
